### ISSUE TITLE
Using the play() method on mobile

### ISSUE THREAD

**Issue by adamsea** [embedly/player.js#13]
Hello,

There seems to be an issue with playing embeds on mobile using the `play()` method, the code I'm using looks something like this:

    /* other methods */

    setupPlayer: function() {
        var iframe = this.$('.embedly-embed');
        this.player = new playerjs.Player(iframe[0]);
        this.player.on('ready', _.bind(this.playVideo, this));
    },

    playVideo: function() {
        if (this.player && this.player.supports('method', 'play')) {
            this.player.play();
        }
    }

    /* rest of the object definition */

I've tested with a YouTube video - What happens is the player loads the video, and then there's just a black container with the video title at the top.  Clicking the video title then gives me the option to open in chrome or the youtube app (typical link handling for the mobile browser).

However, if I don't call `this.player.play()` on mobile, and just load the embed, then tap it, it will play as expected.  Have you seen anything like this before?  Any help as to the cause of this is appreciated, the video is an embedly iframe so I'm a bit mystified by the breakage.

Thanks!
-Eric

**Comment by screeley** [comment]
Hi Eric,

You cannot autoplay video on iOS, you should however be able to play the video on a user action. i.e. click on a button to play. 

If you are in app you can use something like this: http://embed.ly/docs/api/features/mobile#ios
