### ISSUE TITLE
hide youtube controls

### ISSUE THREAD

**Issue by jaequery** [embedly/player.js#14]
Hi, is there a way to disable showing the youtube controls?
Normally with youtube api, I'd pass in JSON option of controls: 0 but do not know how I can do the same with embedly.

Currently I am using the extract() and then appending the response media.html into the dom like so:

```
$.embedly.extract('https://www.youtube.com/embed/'+videoid, {
                    query: {
                        width: w,
                        height: h,
                        controls: 0 // <--- was hoping this would do the trick but did not
                    }
                })
```

Looking forward to your reply, many thanks.

Best,
Jae

**Comment by screeley** [comment]
Embedly specific question, so closing.
