### ISSUE TITLE
getCurrentTime to return each second

### ISSUE THREAD

**Issue by jaequery** [embedly/player.js#17]
Currently getCurrentTime() returns back in milliseconds. 
Is there a way to make this seconds instead of milliseconds?

And with the timeupdate listener, is there a way to make this return response once per second?

**Comment by screeley** [comment]
> Is there a way to make this seconds instead of milliseconds?

No, but you can just round the return value. i.e

    player.getCurrentTime(function(milliseconds){
        var seconds = Math.floor(milliseconds);
     });

> And with the timeupdate listener, is there a way to make this return response once per second?

No. The rate is dependent on the provider and in case of HTML5 video, the browsers. It's normally around every 300 milliseconds.
