### ISSUE TITLE
ready event is not been fired

### ISSUE THREAD

**Issue by yossyr** [embedly/player.js#21]
I have page with an Iframe, i have attached the player to the iframe, but the ready event is never beed fired.
the same code if working perfectly on other pages for the same site!

here is the code:

<script type="text/javascript" src="//cdn.embed.ly/player-0.0.10.min.js"></script>

<script>
/*
 * This script must run on the window load event. We need to wait for the 
 * embed.ly iframes to be loaded before we can attach the event listeners.
 */

(function(){
    
    var globalProgressMarkers = [5,25,50,75,90];
    var EVENT_CATEGORY = "YouTube Video";
    var EVENT_ACTION_PLAY = "play";
    var EVENT_ACTION_PAUSE = "pause";
    var EVENT_ACTION_PROGRESS = "progress";

    /*
     * Given a video url, extract the url=? parameter
     */
    function getVideoURL(link) {
        var name = "url";
        name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
        var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
            results = regex.exec(link);
        return results === null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
    }

    /*
     * Sets up event listeners for an embed.ly iframe
     */
    function setupEmbedly(iframe){
        //Create the API object
        var p = new playerjs.Player(iframe);
        var videoURL = getVideoURL(p.elem.src);
        
        //Set up progress markers for this video
        var pgm = [];
        for(var i = 0; i < globalProgressMarkers.length; i++){
            pgm.push({
                value: globalProgressMarkers[i],
                fired: false
            });
        }

        p.on('ready', function(){     
         console.log("ready iframe");
            p.on('play', function(){
                dataLayer.push({
                    "event": "gaEvent",
                    "gaEventCategory": EVENT_CATEGORY,
                    "gaEventAction": EVENT_ACTION_PLAY,
                    "gaEventLabel": videoURL,
                    "gaEventValue": 0,
                    "gaEventNonInteraction": false
                });
            });
            
            p.on('pause', function(){
                dataLayer.push({
                    "event": "gaEvent",
                    "gaEventCategory": EVENT_CATEGORY,
                    "gaEventAction": EVENT_ACTION_PAUSE,
                    "gaEventLabel": videoURL,
                    "gaEventValue": 0,
                    "gaEventNonInteraction": false
                });
            });  
            
            p.on('timeupdate', function(data){
                
                var progressPct = Math.round((data.seconds/data.duration)*100);
                for(var i = 0; i < pgm.length; i++){
                    var marker = pgm[i];
                    if(progressPct >= marker.value && !marker.fired){

                        dataLayer.push({
                            "event": "gaEvent",
                            "gaEventCategory": EVENT_CATEGORY,
                            "gaEventAction": EVENT_ACTION_PROGRESS+' '+marker.value+'%',
                            "gaEventLabel": videoURL,
                            "gaEventValue": 0,
                            "gaEventNonInteraction": false
                        });                        
                        
                        marker.fired = true;
                    }
                }
 
            });
            
        });    
    }
    //Loop through all iframes, and if any of them is a embed.ly embed, track it.
    var iframes = document.getElementsByTagName('iframe');
    for (var i = 0; i < iframes.length; i++) {
        if (iframes[i].src.indexOf('//cdn.embedly.com') > -1) { 
          setupEmbedly(iframes[i]);
        }
    }          
})();
</script>

**Comment by screeley** [comment]
@yossyr can you create a jsfiddle with the issue?

**Comment by yossyr** [comment]
@screeley 
you can see it at
https://www.teachforamerica.org/about-us/our-mission

**Comment by screeley** [comment]
Not sure what's going on, but it will work in a clean environment:
https://jsfiddle.net/y8kdLhyk/

I'm guessing something else is going on the the JS on that page?

On Mon, Jun 15, 2015 at 9:30 AM, yossyr <notifications@github.com> wrote:

> @screeley <https://github.com/screeley>
> you can see it at
> https://www.teachforamerica.org/about-us/our-mission
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/embedly/player.js/issues/21#issuecomment-112070738>.
>



-- 
Sean Creeley | Co-Founder Embedly
100 North Washington St #503 | Boston 02114
415.891.9917 | sean@embed.ly | @screeley
http://embed.ly | @embedly

**Comment by amillward** [comment]
I'm also having this problem

**Comment by screeley** [comment]
@amillward We actually removed player.js support for cards. But we will be adding it back shortly. 

Sorryyyyy.

**Comment by screeley** [comment]
@amillward We added a new method embedly('player'): https://jsfiddle.net/1mmz99t9/1/

**Comment by virajsonagra** [comment]
Hi
I have three  video tag in my html5 i want it to autoplay when it scroll. Please find attachment when i am trying  to create object it is giving me error playerjs.HTML5Adapter($elem);    "TypeError: video.addEventListener is not a function "  in player-0.0.11.min.js  Please give me solution.
in scroll.js i made following 2 changes

       $(document).on('ready', function(){
           var scroller = new Scroller($('.video'));
         });


        Scroller.prototype.init = function(iframes){
         this.data = [];
    
    // create a player for each of the iframes.
    iframes.each($.proxy(function(i, elem){
      var $elem = $(elem);
      // create the player.
    
      var player = new  playerjs.HTML5Adapter($elem);   
      //Giving me error here. <<----
      
      //      var player = new playerjs.Player(elem);
      // when the player is ready, add it to the rotatation
      player.on('ready', function(){
        player.unmute();
        this.add($elem, player);
      }, this);
      
    }, this));

    // Listen to the scroll events.
    this.listen();
  };
