### ISSUE TITLE
Compatibility Tester randomly passes/fails

### ISSUE THREAD

**Issue by lemmycaution** [embedly/player.js#22]
Hello there, 

I'm trying to implement receiver.js into our player code. However, tests on compatibility tester are passing or failing randomly, against same code. 

Any thought much appreciated, thanks.

**Comment by screeley** [comment]
Generally this is a timing issue, if the embed doesn't respond fast enough the test will fail. 

You can see the tests here: https://github.com/embedly/player.js/blob/gh-pages/scripts/test.js#L163

**Comment by lemmycaution** [comment]
Hey, thanks for super prompt answer. Actually it always passes `ready`, and if it pass `addEventListener` then passes everything too, but if it fails on `addEventListener` then fails obviously. Still not sure actual reason but 
```
receiver.emit('timeupdate', { data: {
  seconds: audio.currentTime,
  duration: audio.duration
}})
``` 
returns false on failed attempts. I saw that if receiver.eventListeners hasn't it's own property or listener it returns false but no idea why it has not related listeners.

**Comment by screeley** [comment]
You might be sending timeupdate events too quickly. They should 1 every 200-300 milliseconds, so if you are pushing a ton the count will be off here:

https://github.com/embedly/player.js/blob/gh-pages/scripts/test.js#L183

**Comment by lemmycaution** [comment]
Hmm, ok I have tried but still failing sometimes, however, all methods and events working actually if I try manually and that's good enough for me, closing issue. Thank you again.
