### ISSUE TITLE
Is player.js dead?

### ISSUE THREAD

**Issue by franz976** [embedly/player.js#27]
Hi
almost all the demos on playerjs.io just don't work anymore...
For instance this one

http://playerjs.io/music.html

but everyone of them just don't work. Any hint?

**Comment by screeley** [comment]
All set, we were actually caught by our own API blocking.

**Comment by franz976** [comment]
Thank you so much.
Does Player.js works on mobile also? I've read about some issues with youtube videos autoplay...

**Comment by screeley** [comment]
Most mobile platforms do not allow videos to autoplay or play via javascript events. All other events tend to perform normally.
