### ISSUE TITLE
Embed.ly dependencies

### ISSUE THREAD

**Issue by franz976** [embedly/player.js#28]
I'm trying to use player.js without using embed.ly to embed videos and audio stuff, so the <iframe> looks simply like this:

<iframe width="420" height="315" src="https://www.youtube.com/embed/1_rD1LeECDE" frameborder="0" allowfullscreen></iframe>
 
...But player.js ignores the previous iframe. 

Is using embed.ly mandatory?

**Comment by screeley** [comment]
YouTube does not support Player.js directly. Embedly creates a wrapper around their Player API to make it compatible with Player.js.

You can see their Player API documentation here: https://developers.google.com/youtube/iframe_api_reference?hl=en
