### ISSUE TITLE
Playerjs for videojs via embedly

### ISSUE THREAD

**Issue by gabesoft** [embedly/player.js#29]
I'm using the current videojs adapter to add playerjs functionality to our player. Everything works fine when using the player directly but it does not work when used via embedly here is a sample url that works

http://playerjs.io/test.html?url=http%3A%2F%2Fwww.slideshare.net%2Fslideshow%2Fembed_code%2Fkey%2FIx0GLB4uRp7atO

but the same video when used via embely does not pass all tests

http://playerjs.io/test.html?url=http%3A%2F%2Fcdn.embedly.com%2Fwidgets%2Fmedia.html%3Fsrc%3Dhttps%253A%252F%252Fwww.slideshare.net%252Fslideshow%252Fembed_code%252Fkey%252FIx0GLB4uRp7atO%26url%3Dhttp%253A%252F%252Fwww.slideshare.net%252Fslideshow%252Fembed_code%252Fkey%252FIx0GLB4uRp7atO%253Fconviva%253Dstaging%26image%3Dhttp%253A%252F%252Fcdn.slidesharecdn.com%252Fss_thumbnails%252F160303buildinghighperformanceteams-160324195034-lva1-app6892-video-thumbnail.jpg%253Fcb%253D1458849576%26key%3Dinternal%26type%3Dtext%252Fhtml%26schema%3Dslideshare

Is there something special I would need to do in the embedly case?

Here's the code that I use to initialize the videojs adapter
``` javascript
    const videojsPlayer = videojs(...);
    videojsPlayer.ready(() => {
      const playerjs = new playerjs.VideoJSAdapter(videojsPlayer);
      playerjs.ready();
    });
```

**Comment by screeley** [comment]
Hi @gabesoft, Can you shoot an email to support@embed.ly. This is an Embedly specific question.

**Comment by gabesoft** [comment]
Thanks
