### ISSUE TITLE
http://playerjs.io/test.html is broken for short videos

### ISSUE THREAD

**Issue by SeanHayes** [embedly/player.js#33]
I'm testing an embed for a gif that's been converted to mp4. It's really short, less than 3 seconds, so the setCurrentTime and getCurrentTime tests fail. I'm using the HTML5Adapter.

Example: http://playerjs.io/test.html?url=https%3A%2F%2Fstark.riffsy.com%2Fdev%2Fsean%2Frx.fcgi%2Fembed%2F4989370%3Fplaypause%3D1%26autoplay%3D1%26muted%3D1

**Comment by SeanHayes** [comment]
Why was this closed? The bug hasn't been fixed.

**Comment by screeley** [comment]
Sorry, should have marked as won't fix. Happy to accept a pull request, but using a longer video solves the problem nicely.
