### ISSUE TITLE
Controlling Multiple Sources in iOS

### ISSUE THREAD

**Issue by richsancho** [embedly/player.js#37]
Hello,

We are attempting to leverage player.js to control several Megaphone embeds. In the jsfiddle below, you can see that this works fine on desktop, but only plays back the first interaction in iOS (we've tested ios 9 and 10):

https://jsfiddle.net/hyr4kd5w/5/

Any info or insight would be appreciated. Thanks in advance.

**Comment by screeley** [comment]
Hello, 

Sadly, you can't use player.play() on iOS unless you are in a webview. iOS considers it an "autoplay" when you send an event down through postMessage to play a video.

If you are in a webview, see: https://developer.apple.com/reference/uikit/uiwebview/1617954-mediaplaybackrequiresuseraction

**Comment by richsancho** [comment]
Hi @screeley,

Thanks for the reply, much appreciated - is that true of audio sources (not video)? Because if you take a look at the fiddle, it *does* fire in iOS safari (non-webview) - but only fires once.

After several button taps, the others will sporatically/ eventually fire as well, but non-consistently.
