### ISSUE TITLE
Adding custom methods to playerJS interface?

### ISSUE THREAD

**Issue by nickfujita** [embedly/player.js#43]
When integrating playerJS to use with an iframe and a custom PlayerJS adapter, I would like to be able to add custom methods to the player interface. One such example is if we wanted to trigger events within the iframe related to video, but a part of the standard methods (play, pause, mute).

I was able to rig up a working 'solution' with what is already available, but the format seems like it is abusing the available methods.

Code inside iframe
- Add custom method name to `playerjs.METHODS` object.
- Set `receiver.on` listener for custom method name with a callback function

Code outside iframe
- Call the method with `player.send({method: '<custom method name>'});`
    - With an argument to pass to method: `player.send({method: '<custom method name>', value: '<first argument value>'});`

While this is working, my gut feeling is that there must be a better way. Is there already a prescribed way for adding custom methods to the playerJS interface, as I could not find it in the documentation? The existence of the `supports` method on the player seems to suggest that they should be a way to pass custom methods that can change depending on the adapter being used?

Any help would be greatly appreciated.

**Comment by ima007** [comment]
@nickfujita You can pass a list of all of your events and methods to the `receiver` constructor:
```
playerjs.Receiver = function(events, methods){
```
At that point, I imagine you could do:
```
receiver.on('my_custom_method', function(paramOrCallback) { ... });
```

**Comment by nickfujita** [comment]
Thanks for confirming! Just to close the loop on this.

The way to call this from the sender side is:
`player.send({method: '<METHOD_NAME>'});`

You can also send a single argument as follows:
`player.send({method: '<METHOD_NAME>', value: '<FIRST_ARGUMENT>'});`

Alternative to sending the method name in the constructor of the receiver, I have found that adding any custom methods to the playerjs instance works.
`playerjs.METHODS[<METHOD_NAME>] = <REFERENCE_TO_METHOD>;`
