### ISSUE TITLE
Changing iframe / playerjs source

### ISSUE THREAD

**Issue by jgraniero** [embedly/player.js#45]
Is there a recommended way for changing the src of the iframe / playerjs object?

I basically have a playerjs embed as a preview in an editor I'm building.  As the user changes the configuration in the editor, I need to replace the playerjs src with a new url that reflects the updated config.

When the user updates the embed config, I save the current playback position of the embed using `player.getCurrentTime`, remove the old iframe, create a new one, and drop it in the dom where the old one was.

In the ready callback for the new playerjs object, I attempt to set the time I had saved so that the embed begins playing where it left off before the user changed the config.  Sometimes this works, but more often than not the position of the embed doesn't change.  

It seems like some race condition.  If i set the position of the new playerjs object a second or two after `ready` fires, everything works fine.

Edit: It's probably worth mentioning that `ready` does fire reliably every time, just that most of the time the playerjs methods I call inside of  `ready` have no effect.  It's as if the player isn't actually ready or the messages are somehow being sent to the player in the iframe I removed.

**Comment by screeley** [comment]
Create a new iframe and player each time, don't try and reuse the player.
