### ISSUE TITLE
setCurrentTime() broken for Cards; play() broken for Media Iframes

### ISSUE THREAD

**Issue by NTag** [embedly/player.js#46]
Hello,

In your [JSFiddle](https://jsfiddle.net/fexnhqbd/), when I click on "Play", only the first player (from the Card) plays. The second one seems to play and pause immediately.

In the code, if I replace `player.play()` by `player.setCurrentTime(30)`, when I click on "Play", only the second player (from the Media Iframe) seeks to 30 seconds, the first one doesn't move.

Thank you very much!

**Comment by NTag** [comment]
Even worse, if in the Card, I replace the Vimeo link by a [YouTube link](https://www.youtube.com/watch?v=Lp_MOE-GQcQ), and replace `player.play()` by `player.setCurrentTime(30)`, when I click on "Play", JavaScript errors appear from the Youtube player `Uncaught TypeError: a.g.o(...).toFixed is not a function [...]`.

**Comment by screeley** [comment]
This is a better example for cards player: https://jsfiddle.net/fexnhqbd/21/
