### ISSUE TITLE
'progress' is not working and I can't find reason.

### ISSUE THREAD

**Issue by bernoulli26** [embedly/player.js#47]
Hi guys, I want to use playerjs for my project. But I'm not good at js and jquery. So I'm learning while testing some codes. For my project, I interested in 'progress' event which notice me how many buffered.
I wrote this code and didn't work at all.
`player.on('progress', function(){
  console.log(percent);
});`
How can I correct this?

**Comment by screeley** [comment]
use the `timeupdate` event instead.

**Comment by bernoulli26** [comment]
Has `timeupevent` property about buffering?
I thought `timeupevent` have only about played time.

**Comment by screeley** [comment]
The `progress` event is very poorly supported across providers. It's not an event we focus on.
