### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by davidurco** [embedly/player.js#85]
Hello, I'm getting this weird error with youtube video cards. Any idea why this is happening?
![image](https://user-images.githubusercontent.com/23614886/98727780-c7432680-2398-11eb-939e-7cc59127962a.png)

**Comment by davidurco** [comment]
You can also inspect the embed.ly link [here](https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fcdn.embedly.com%2Fwidgets%2Fmedia.html%3Fsrc%3Dhttps%253A%252F%252Fwww.youtube.com%252Fembed%252FDxR4PqPlgzQ%253Ffeature%253Doembed%26display_name%3DYouTube%26url%3Dhttps%253A%252F%252Fwww.youtube.com%252Fwatch%253Fv%253DDxR4PqPlgzQ%26image%3Dhttps%253A%252F%252Fi.ytimg.com%252Fvi%252FDxR4PqPlgzQ%252Fhqdefault.jpg%26args%3Dshowinfo%253D0%26key%3Dfd92ebbc52fc43fb98f69e50e7893c13%26type%3Dtext%252Fhtml%26card%3D1%26schema%3Dyoutube&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DDxR4PqPlgzQ&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FDxR4PqPlgzQ%2Fhqdefault.jpg&args=showinfo%3D0&key=fd92ebbc52fc43fb98f69e50e7893c13&type=text%2Fhtml&schema=youtube). Embedded youtube video should pop up but instead there is an error in console.

**Comment by lselden** [comment]
Did you try to double embed an embedly link? Maybe you want [this](https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FDxR4PqPlgzQ%3Ffeature%3Doembed&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DDxR4PqPlgzQ&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FDxR4PqPlgzQ%2Fhqdefault.jpg&args=showinfo%3D0&key=fd92ebbc52fc43fb98f69e50e7893c13&type=text%2Fhtml&card=1&schema=youtube) instead?

**Comment by davidurco** [comment]
@lselden what do you mean? The link that I've provided is automatically generated, I'm not controlling it.

**Comment by davidurco** [comment]
**SOLVED!** I was trying to double embed an embedly link. I'm closing this issue.
